name: Documentation Content 
description: Report an issue related to the documentation content on https://pytorch-ignite.ai
labels: ["bug: pending triage", "type: content"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe documentation issue
      description: |
        A clear and concise description of what the documentation content issue is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
        **Please note that the issues of the contents inside `guides` and `tutorials` must be reported to https://github.com/pytorch-ignite/examples**.
      placeholder: Documentation issue description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to any relevant https://pytorch-ignite.ai page is helpful if you have one.
    validations:
      required: true
