name: linkcheck

on:
  push:
    branches:
      - main
  pull_request:

# https://gohugo.io/hosting-and-deployment/hosting-on-github/#build-hugo-with-github-action
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.88.1"
          extended: true

      - name: Build
        run: bash scripts/build.sh

      - run: curl https://htmltest.wjdp.uk | bash
      - run: ./bin/htmltest dist
