name: submodule

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run every 6 hours Every Day
    - cron: "0 0/6 * * *"

jobs:
  check-update:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - run: bash ./scripts/check_submodules.sh

  check-ipynb-to-md:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: |
          pip install pip wheel setuptools -Uqq
          pip install -r ./scripts/requirements.txt -Uqq

      - name: Check tutorials
        run: |
          bash ./scripts/nb_to_md.sh static/examples tmp/tutorials
          diff -r content/tutorials tmp/tutorials --exclude=_index.md

      - name: Check how-to-guides
        run: |
          bash ./scripts/nb_to_md.sh static/examples/how-to-guides tmp/how-to-guides
          diff -r content/how-to-guides tmp/how-to-guides --exclude=_index.md

  auto-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: |
          pip install pip wheel setuptools -Uqq
          pip install -r ./scripts/requirements.txt -Uqq

      - run: git submodule update --remote -- static/examples
      - run: bash ./scripts/nb_to_md.sh static/examples src/tutorials
      - run: bash ./scripts/nb_to_md.sh static/examples/how-to-guides src/guide

      - uses: peter-evans/create-pull-request@v3
        with:
          title: '[automated] Submodule update'
          body: This is an automated pull request.
          commit-message: 'chore: update submodules'
          branch: submodule-update
